name = "Advanced Remote Control"
author = "Brett"
prefix = "arc"
mainprefix = "z"

[hemtt.launch.default]
workshop = [
    "3499977893", # ADT
    "450814997", # CBA
    "463939057", # ACE3
]

[hemtt.launch.cup]
extends = "default"
workshop = [
    "497660133", # CUP Weapons
    "497661914", # CUP Units
    "541888371", # CUP Vehicles
]
